spring:
  profiles:
    active: local

security:
  jwt:
    secret: a7T8mQ2xL5rH9jK0pB3zW1yNxV6c4oFhJkSiZPlGsYb
  internal:
    token: YWhmaWZ1QUtFSVVKRmt3bGtkbHdvS1NV

integration:
  rest:
    auth-service:
      url: AFI-BMSTU-auth-service
      token: YmtnamdvaU9RZmpza2pmVUZqZ2hnMTI4NGpK