spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      group-id: "user-creation-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    listener:
      ack-mode: manual

security:
  jwt:
    secret: a7T8mQ2xL5rH9jK0pB3zW1yNxV6c4oFhJkSiZPlGsYb
  internal:
    token: YWhmaWZ1QUtFSVVKRmt3bGtkbHdvS1NV

integration:
  rest:
    auth-service:
      url: AFI-BMSTU-auth-service
      token: YmtnamdvaU9RZmpza2pmVUZqZ2hnMTI4NGpK
  kafka:
    topic:
      user-creation: user-creation-topic
      user-delete: user-delete-topic